import './globals.scss';
import Header from './components/Header';
import Footer from './components/Footer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {
        <>
          <title>TheMarketplace</title>
          <meta content="width=device-width, initial-scale=1" name="viewport" />
          <meta name="description" content="Generated by annalitvinenko9@gmail.com on next app" />
          <link rel="icon" href="/Storefront.svg" />
        </>
      }
      <head />
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
